/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 註冊新帳號
         * @description 以 email + 密碼 + displayName 建立新帳號（`role=USER`、`authProvider=LOCAL`、`theme=light`、`isActive=true`）。
         *     需 `AdminSettings.registrationOpen=true`，否則回 403。
         *     密碼需滿足：長度 ≥ 8 + 不命中 top-10,000 弱密碼清單。
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 以 email + 密碼登入
         * @description 驗證成功則下發 httpOnly cookie（`token=<JWT>; HttpOnly; Secure; SameSite=Strict; Max-Age=604800`）。
         *     回應本體僅含 `user`，**不** 含 token 明文。
         *
         *     **限流規則（FR-021）**：同 IP 每分鐘最多 5 次失敗；第 6 次觸發 429 + `Retry-After` + `retryAfterSeconds`。
         *     成功登入不計入失敗次數（`skipSuccessfulRequests`）。
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登出當前裝置
         * @description 後端以 `Set-Cookie: token=; Max-Age=0` 清除 auth cookie。
         *     不維護 token 黑名單；其他裝置的既有 cookie 仍有效至其自然到期（或密碼變更觸發全裝置失效）。
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 取得當前使用者資訊
         * @description Single source of truth；前端可據此判斷是否已登入（200 = 已登入、401 = 未登入）。
         *     回傳欄位不含 `password`、`passwordChangedAt`、`googleId`。
         */
        get: operations["getCurrentUser"];
        /**
         * 更新顯示名稱或主題
         * @description 僅允許更新 `displayName` 與 `theme`；其他欄位（email、role、password、isActive）**不** 被接受。
         */
        put: operations["updateCurrentUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 變更密碼（需提供舊密碼）
         * @description 於同一資料庫 transaction 更新 `password` 與 `passwordChangedAt`；
         *     回應時以 `Set-Cookie: token=; Max-Age=0` **清除當前 cookie**——
         *     使用者（及其他裝置）**必須** 重新登入（FR-020b / FR-020c）。
         *     新密碼需滿足與註冊相同的密碼規則。
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /**
             * @description 使用者唯一識別（cuid）
             * @example clxabc123def456
             */
            id: string;
            /**
             * Format: email
             * @description 登入 email（已正規化為小寫）
             * @example alice@example.com
             */
            email: string;
            /** @example Alice Chen */
            displayName: string;
            /**
             * @default USER
             * @enum {string}
             */
            role: "ADMIN" | "USER" | "VIEWER";
            /**
             * @default LOCAL
             * @enum {string}
             */
            authProvider: "LOCAL" | "GOOGLE";
            /**
             * @default light
             * @enum {string}
             */
            theme: "light" | "dark";
            /**
             * @description 帳號啟用旗標；`false` 代表已被管理員停用
             * @default true
             */
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        RegisterRequest: {
            /**
             * Format: email
             * @description 將於伺服器端經 trim + lowercase 正規化
             * @example Alice@Example.com
             */
            email: string;
            /**
             * @description 長度 ≥ 8（UTF-8 code points）；
             *     **不** 能命中內建 top-10,000 常見弱密碼清單。
             *     伺服器以 SHA-256 pre-hash + bcrypt(cost=12) 儲存。
             * @example Str0ngPassword!
             */
            password: string;
            /**
             * @description trim 後非空
             * @example Alice
             */
            displayName: string;
        };
        RegisterResponse: {
            user: components["schemas"]["User"];
        };
        LoginRequest: {
            /**
             * Format: email
             * @example alice@example.com
             */
            email: string;
            /** @description 登入階段不做長度/弱密碼檢查（避免正規化差異導致合法使用者被擋） */
            password: string;
        };
        /**
         * @description **注意**：無 `token` 欄位。JWT 已透過 `Set-Cookie` header 下發，
         *     前端 JavaScript 無法也無須讀取 token。
         */
        LoginSuccessResponse: {
            user: components["schemas"]["User"];
        };
        UpdateProfileRequest: {
            displayName?: string;
            /** @enum {string} */
            theme?: "light" | "dark";
        };
        ChangePasswordRequest: {
            oldPassword: string;
            /** @description 長度 ≥ 8 + 不命中弱密碼清單 */
            newPassword: string;
        };
        GenericSuccess: {
            /** @example 操作成功 */
            message: string;
        };
        GenericError: {
            /** @description 使用者可見的繁體中文錯誤訊息 */
            message: string;
        };
        ValidationError: {
            /** @example 輸入驗證失敗 */
            message: string;
            errors: {
                /**
                 * @description 欄位名（JSON path）
                 * @example email
                 */
                path: string;
                /**
                 * @description 該欄位的繁中錯誤訊息
                 * @example email 格式錯誤
                 */
                message: string;
            }[];
        };
        RateLimitedResponse: {
            /** @example 登入嘗試次數過多，請稍後再試 */
            message: string;
            /**
             * @description 距限流窗口結束的整數秒數。
             *     與 `Retry-After` header 的值完全一致。
             *     前端可據此顯示倒數。
             * @example 45
             */
            retryAfterSeconds: number;
        };
    };
    responses: {
        /** @description 未登入、cookie 過期、或因密碼變更而失效 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["GenericError"];
            };
        };
        /**
         * @description CSRF 防護攔截（`Origin` header 缺失或不在白名單）。
         *     `SameSite=Strict` cookie 於一般跨站情境已阻擋請求；此 403 僅於非標準 UA 觸發。
         */
        CsrfForbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "message": "請求來源不被允許"
                 *     }
                 */
                "application/json": components["schemas"]["GenericError"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description 註冊成功；**不** 自動登入，使用者需另外呼叫 `/auth/login`。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description 輸入驗證錯誤（email 格式、密碼長度/弱密碼、displayName 空） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description 公開註冊已關閉（`AdminSettings.registrationOpen=false`） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "目前不開放註冊"
                     *     }
                     */
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            /** @description Email 已存在 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "帳號已存在"
                     *     }
                     */
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登入成功；cookie 已透過 `Set-Cookie` 下發。 */
            200: {
                headers: {
                    /**
                     * @description 下發 JWT cookie
                     * @example token=eyJhbGciOi...; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=604800
                     */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginSuccessResponse"];
                };
            };
            /** @description 輸入驗證錯誤 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description 帳號不存在或密碼錯誤（統一訊息，避免 enumeration） */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "帳號或密碼錯誤"
                     *     }
                     */
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            /** @description 帳號已被管理員停用 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "帳號已被停用"
                     *     }
                     */
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            /** @description 限流觸發；`Retry-After` header + `retryAfterSeconds` body */
            429: {
                headers: {
                    /**
                     * @description 距限流窗口結束的整數秒數（RFC 9110）
                     * @example 45
                     */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitedResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 登出成功；cookie 已清除。 */
            200: {
                headers: {
                    /**
                     * @description 清除 auth cookie
                     * @example token=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0
                     */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "已登出"
                     *     }
                     */
                    "application/json": components["schemas"]["GenericSuccess"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["CsrfForbidden"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 目前使用者的個人資料 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description 更新後的使用者資料 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description 輸入驗證錯誤（displayName 空、theme 非法值） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["CsrfForbidden"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description 密碼變更成功；cookie 已清除，需重新登入。 */
            200: {
                headers: {
                    /**
                     * @description 清除 auth cookie（強制重新登入）
                     * @example token=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0
                     */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "密碼已更新，請重新登入"
                     *     }
                     */
                    "application/json": components["schemas"]["GenericSuccess"];
                };
            };
            /** @description 新密碼驗證失敗（長度或弱密碼） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description 未登入，或舊密碼錯誤（統一為 401 避免密碼 oracle） */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "帳號或密碼錯誤"
                     *     }
                     */
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            403: components["responses"]["CsrfForbidden"];
        };
    };
}
